---
title: "Assignment 3"
author: "Seth Friesz"
date: "9/12/2021"
output: html_document
---

```{r warning=FALSE, message = FALSE}
library(readxl)
library(tidyverse)
library(ggplot2)
library(plotly)
library(anytime)

PATH = "/Users/sethfriesz/Documents/R Scripts/CoVid-19_app"

Census <- read_excel(
  paste0(PATH, "/Census.xlsx")
)

#JHU_09_06_2021 <- read_excel("COVID_data_State_level/JHU_09-06-2021.xlsx")

US_counties = read.csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv')

#Voting <- read_excel("COVID_data_State_level/Voting.xlsx")
#Month_difference <- read_excel("COVID_data_State_level/Month_difference.xlsx")

#x = US_counties[2,1]
#as.character(substr(x, 4, 8))
#length(US_counties$UID)
for (x in 1:length(US_counties$UID)){
  US_counties[x,5] = as.character(substr(US_counties[x,1], 4, 8))
}

US_counties[2586,6] = "Shannon"
US_counties[87,6] = "Wade Hampton"

US_counties[2586,5] ='46113'
US_counties[87,5]  = '02270'
#JHU_09_06_2021 = JHU_09_06_2021[-c(3, 10, 14,15,40,45,53), ]
Census = Census[-c(57),]
```

```{r}
# for (x in unique(JHU_09_06_2021$Province_State))
#   JHU_09_06_2021[JHU_09_06_2021$Province_State == x, 'Population'] = Census[Census$NAME == x, "POPESTIMATE2019"]
# for (x in unique(JHU_09_06_2021$Province_State))
#   JHU_09_06_2021[JHU_09_06_2021$Province_State == x, '2020 Vote'] = Voting[Voting$State == x, "Vote"]
# for (x in unique(JHU_09_06_2021$Province_State))
#   JHU_09_06_2021[JHU_09_06_2021$Province_State == x, 'Region'] = Census[Census$NAME == x, "REGION"]
# 
# # if (JHU_09_06_2021$Region == as.character((1))){
# #   JHU_09_06_2021$Region = 'Northeast'
# # } else if (JHU_09_06_2021$Region == as.character(2)){
# #   JHU_09_06_2021$Region = 'Midwest'
# # } else if (JHU_09_06_2021$Region == as.character(3)){
# #   JHU_09_06_2021$Region = 'South'
# # } else if (JHU_09_06_2021$Region == as.character(4)){
# #   JHU_09_06_2021$Region = 'West'
# # }
# 
# JHU_09_06_2021$Case_Pop_Ratio = (JHU_09_06_2021$Confirmed/JHU_09_06_2021$Population)*100
# JHU_09_06_2021$Death_Pop_Ratio = (JHU_09_06_2021$Deaths/JHU_09_06_2021$Population)*100

```

1 - Northeast
2 - Midwest
3 - South
4 - West

```{r}
# BoxnWhiskCase <- ggplot(JHU_09_06_2021, aes(x = Region,y = Case_Pop_Ratio, fill = Region)) + 
#   geom_boxplot() + theme_dark()+ggtitle("Case/Population ratio boxplot of regions") 
# BoxnWhiskCase
# 
# BoxnWhiskDeath <- ggplot(JHU_09_06_2021, aes(x = Region,y = Death_Pop_Ratio, fill = Region)) + 
#   geom_boxplot() + theme_dark()+ggtitle("Death/Population ratio boxplot of regions") 
# BoxnWhiskDeath

```


```{r}
US_states_14_days_final = Census[6:nrow(Census), 'NAME']

```


```{r}

US_counties_14_days = US_counties[, seq_len(ncol(US_counties)) %% 14 == 7]
for (x in unique(Census$NAME)){
  for (y in 2:ncol(US_counties_14_days)){
    #print(x)
    #print(y)
    US_states_14_days_final[US_states_14_days_final$NAME == x,y] = sum(US_counties_14_days[US_counties_14_days$Province_State == x, y]) / (Census[Census$NAME == x,6]/100000)
    
    
  }
  
}


list_of_names = c('State', '01/31/2020','02/14/2020','02/28/2020','03/13/2020','03/27/2020','04/10/2020','04/24/2020','05/08/2020','05/22/2020','06/05/2020','06/19/2020','07/3/2020','07/17/2020','07/31/2020','08/14/2020','08/28/2020','09/11/2020','09/25/2020','10/9/2020','10/23/2020','11/6/2020','11/20/2020','12/4/2020','12/18/2020','01/01/2021','1/15/2021','1/29/2021','2/12/2021','2/26/2021','3/12/2021','3/26/2021','4/9/2021','4/23/2021','5/7/2021','5/21/2021','6/4/2021','6/18/2021','7/2/2021','7/16/2021','7/30/2021','8/13/2021','8/27/2021','9/10/2021','9/24/2021','10/8/2021','10/22/2021', '11/5/2021','11/19/2021','12/03/21','12/17/21','12/31/21')

colnames(US_states_14_days_final)<- list_of_names

states_longer = US_states_14_days_final %>% pivot_longer(!State, names_to = "date", values_to = "count")
states_longer$date <- anydate(states_longer$date)
#states_longer$date
```


```{r}
xy = c('North Dakota','South Dakota')
p <- ggplot(states_longer[states_longer$State == xy,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() +theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
```
```{r}
unique(states_longer['State'])

```


```{r}
p <- ggplot(states_longer[1:430,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() +theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
p <- ggplot(states_longer[431:860,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() + theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
p <- ggplot(states_longer[861:1290,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() + theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
p <- ggplot(states_longer[1291:1720,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() + theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
p <- ggplot(states_longer[1721:2193,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() + theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
#states_longer$date
#states_longer$date <- as.Date(states_longer$date)
```


```{r}
red_case_pop = JHU_09_06_2021[JHU_09_06_2021$`2020 Vote` == 'R', "Case_Pop_Ratio"]
blue_case_pop = JHU_09_06_2021[JHU_09_06_2021$`2020 Vote` == 'B', "Case_Pop_Ratio"]
t.test(red_case_pop,blue_case_pop)
```


```{r}
US_states_14_days_final_test = Census[6:nrow(Census), 'NAME']

```


```{r}

US_counties_14_days = US_counties[, seq_len(ncol(US_counties)) %% 14 == 7]
for (x in unique(Census$NAME)){
  for (y in 2:ncol(US_counties_14_days)){
    #print(x)
    #print(y)
    US_states_14_days_final_test[US_states_14_days_final_test$NAME == x,y] = sum(US_counties_14_days[US_counties_14_days$Province_State == x, y])
    
    
  }
  
}


list_of_names = c('State', '01/31/2020','02/14/2020','02/28/2020','03/13/2020','03/27/2020','04/10/2020','04/24/2020','05/08/2020','05/22/2020','06/05/2020','06/19/2020','07/3/2020'
                  ,'07/17/2020','07/31/2020','08/14/2020','08/28/2020','09/11/2020','09/25/2020','10/9/2020','10/23/2020','11/6/2020','11/20/2020','12/4/2020',
                  '12/18/2020','01/01/2021','01/15/2021','01/29/2021','2/12/2021','2/26/2021','3/12/2021','3/26/2021','4/9/2021','4/23/2021','5/7/2021','5/21/2021'
                  ,'6/4/2021','6/18/2021','7/2/2021','7/16/2021','7/30/2021','8/13/2021','8/27/2021','9/10/2021','9/24/2021', '10/8/2021', '10/22/2021'
                  ,'11/5/2021', '11/19/2021','12/3/2021', '12/17/2021','12/31/2021')

colnames(US_states_14_days_final_test)<- list_of_names

states_longer_test = US_states_14_days_final_test %>% pivot_longer(!State, names_to = "date", values_to = "overall")
states_longer_test$date <- anydate(states_longer_test$date)

# for loop to get per 100,000
for (x in unique(states_longer_test$State)){
  states_longer_test[states_longer_test$State == x, "state_population"] = Census[Census$NAME == x, "POPESTIMATE2019"]
}

states_longer_test

```


```{r}
xy = c('California','South Dakota')
p <- ggplot(states_longer_test[states_longer_test$State == xy,], aes(x = date, y = count, group = State, color = State)) +
  geom_line() +theme(axis.text.x = element_text(angle = 90)) + scale_x_date(date_breaks = 'month' , date_labels = "%b-%y")
p
```
